version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432" # Map the default PostgreSQL port to the host
    environment:
      POSTGRES_DB: mengzorDB
      POSTGRES_USER: mentzer
      POSTGRES_PASSWORD: oneset
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres_data:
